ALTER TABLE projects
ADD COLUMN IF NOT EXISTS repository_owner TEXT NOT NULL DEFAULT '';

ALTER TABLE projects
ADD COLUMN IF NOT EXISTS repository_name TEXT NOT NULL DEFAULT '';

ALTER TABLE projects
ADD COLUMN IF NOT EXISTS base_branch TEXT NOT NULL DEFAULT '';

ALTER TABLE projects
ADD COLUMN IF NOT EXISTS service_name TEXT NOT NULL DEFAULT '';

ALTER TABLE projects
ADD COLUMN IF NOT EXISTS dockerfile_path TEXT NOT NULL DEFAULT '';

ALTER TABLE projects
ADD COLUMN IF NOT EXISTS service_type TEXT NOT NULL DEFAULT '';

ALTER TABLE projects
ADD COLUMN IF NOT EXISTS service_port INTEGER NOT NULL DEFAULT 0;

ALTER TABLE projects
ADD COLUMN IF NOT EXISTS container_port INTEGER NOT NULL DEFAULT 0;
