ALTER TABLE resource_usage
ADD COLUMN IF NOT EXISTS cpu_cores FLOAT NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS memory_gb FLOAT NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS replica_count INTEGER NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS pod_uptime_hours FLOAT NOT NULL DEFAULT 0;
