ALTER TABLE users
ADD COLUMN IF NOT EXISTS telegram_username TEXT NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS telegram_chat_id BIGINT NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS telegram_linked_at TIMESTAMPTZ,
ADD COLUMN IF NOT EXISTS telegram_link_code TEXT NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS telegram_link_expires_at TIMESTAMPTZ,
ADD COLUMN IF NOT EXISTS telegram_notifications_enabled BOOLEAN NOT NULL DEFAULT FALSE;
